### ISSUE TITLE
App is getting disabled.

### ISSUE THREAD

**Issue by ovidiulaz7** [leonardoxh/AsyncOkHttpClient#22]
My app is getting disabled while including your library in development mode, installing an apk from outside the Google PlayStore or deploying a build with adb will get it disabled.
Included with:
compile 'com.github.leonardoxh:AsyncOkHttpClient:1.1@aar'

**Comment by leonardoxh** [comment]
Oh hi, thanks for the issue.

I'll recommend you migrate to another library like OkHttpClient, I decide descontinuate this library (like readme says), and I'll not push any commit here or try resolve any issue so, sorry.

I think your problem is related with an old component used on OkHttp version used on this library.

**Comment by ovidiulaz7** [comment]
Yeah, sorry, I was in a hurry and didn't observe the note in the readme file.

Thanks, 
Regards.
